### ISSUE TITLE
Drone build failed

### ISSUE THREAD

**Issue by SeppPenner** [arduino/reference-es#113]
![grafik](https://user-images.githubusercontent.com/9639361/41966295-096173dc-79ff-11e8-8f76-3632fea95e7f.png)

![grafik](https://user-images.githubusercontent.com/9639361/41966309-10fc964e-79ff-11e8-851a-a1e7b5db766f.png)

time="2018-06-27T09:40:19Z" level=fatal msg="Error: you must provide your Drone access token."

**Comment by matteosuppo** [comment]
You should rebase the failing PR on master to see the problem go away

**Comment by SeppPenner** [comment]
Works, see https://github.com/arduino/reference-es/pull/114.
