### ISSUE TITLE
Translate subcategories names

### ISSUE THREAD

**Issue by smellai** [arduino/reference-es#2]
languageCode: "es"
title: "Arduino Reference"

params:
  description: "The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords."
  category:
  - name: "functions"
    intro: "For controlling the Arduino board and performing computations."
    subCategories:
    - name: "Main"
    - name: "Digital I/O"
    - name: "Analog I/O"
    - name: "Zero, Due & MKR Family"
    - name: "Advanced I/O"
    - name: "Time"
    - name: "Math"
    - name: "Trigonometry"
    - name: "Characters"
    - name: "Random Numbers"
    - name: "Bits and Bytes"
    - name: "External Interrupts"
    - name: "Interrupts"
    - name: "Communication"
      child:
      - name: "Serial"
      - name: "Stream"
    - name: "USB"
      child:
      - name: "Keyboard"
      - name: "Mouse"

  - name: "variables"
    intro: "Arduino data types and constants."
    subCategories:
    - name: "Constants"
    - name: "Conversion"
    - name: "Data Types"
    - name: "Variable Scope & Qualifiers"
    - name: "Utilities"

  - name: "structure"
    intro: "The elements of Arduino (C++) code."
    subCategories:
    - name: "Control Structure"
    - name: "Further Syntax"
    - name: "Arithmetic Operators"
    - name: "Comparison Operators"
    - name: "Boolean Operators"
    - name: "Pointer Access Operators"
    - name: "Bitwise Operators"
    - name: "Compound Operators"

**Comment by mario-loza** [comment]
languageCode: "es"
title: "Guía de Referencia de Arduino"

params:
description: "La guía de referencia del lenguaje de programación de Arduino, organizada en Funciones, Variables y Constantes, y palabras clave de Estructura."
category:

name: "funciones"
intro: "Para controlar la tarjeta Arduino y realizar calculos."
subCategories:

name: "Principal"
name: "I/O Digital"
name: "I/O Analógico "
name: "Familia Zero, Due & MKR"
name: "I/O Avanzado"
name: "Tiempo"
name: "Matemáticas"
name: "Trigonometria"
name: "Caracteres"
name: "Números Randomicos"
name: "Bits y Bytes"
name: "Interruptores Externos"
name: "Interruptores"
name: "Comunicación"
child:
name: "Serial"
name: "Stream"
name: "USB"
child:
name: "Teclado"
name: "Mouse"
name: "variables"
intro: "Arduino tipos de datos y constantes."
subCategories:

name: "Constantes"
name: "Conversión"
name: "Tipos de Datos"
name: "Alcance de Variable & Calificadores"
name: "Utilidades"
name: "estructura"
intro: "Los elementos del código de Arduino (C++)."
subCategories:

name: "Estructuras de Control"
name: "Sintaxis Adicional"
name: "Operadores Aritméticos"
name: "Operadores de Comparación"
name: "Operadores Booleanos"
name: "Operadores con punteros  de acceso"
name: "Operadores de Bits"
name: "Operadores Compuestos"

**Comment by smellai** [comment]
Thank you so much! You'll find your translations on https://reference.arduino.cc/reference/es
