### ISSUE TITLE
Translate site texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-es#7]
- Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions.

- Language

- Libraries

- Glossary

- Edit This Page

- The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>.

- Find anything that can be improved? <a href=\"https://github.com/arduino/reference-en\" target=\"_blank\" rel=\"noopener\">Suggest corrections and new documentation via GitHub.</a>

- Doubts on how to use Github? Learn everything you need to know in <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>.

**Comment by omendezmorales** [comment]
Hi @smellai , I'd like to contribute. I'll start with the structure part of the language. I think that I understood the contributing tutorial, so I'll modify one file at a time. Please correct/contact me if there's something I mess with that was not supposed to. Cheers!
Orlando.

**Comment by mario-loza** [comment]
El lenguaje de programación de Arduino se puede dividir en tres grandes partes: estructura, valores (variables y constantes), y funciones.

Lenguaje

Librerias

Glosario

Editar esta Pagina

El testo de Referencia de Arduino tiene licencia <a href="https://creativecommons.org/licenses/by-sa/3.0/\" target="_blank" rel="noopener">Creative Commons Attribution-Share Alike 3.0 License.

Encontraste algo que pueda ser mejorado? <a href="https://github.com/arduino/reference-en\" target="_blank" rel="noopener">sugerir correcciones y nueva documentación vía GitHub.

Dudas en como usar Github? Aprende todo lo que necesitas saber en <a href="https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target="_blank" rel="noopener">este tutorial.

**Comment by smellai** [comment]
Thanks @mario-loza ! You'll find your translations here https://www.arduino.cc/reference/es/

**Comment by Ardumania** [comment]
Hi every body.
I'm going to start translating Language/Functions/Communication/Serial
Feel free for any sugestion.
Greetings from Spain
